services:
  app:
    build: 
      dockerfile: ./DockerFile
    ports:
      - "80:8081"  
    environment:
      DATABASE_URL: postgresql://postgres:blackbank@db:5432/CustomerDB
    depends_on:
      - db  
    networks:
      - app-network

  db:
    image: postgres:14.18
    environment:
      POSTGRES_PASSWORD: blackbank
      POSTGRES_USER: postgres
      POSTGRES_DB: CustomerDB
    ports:
      - "5432:5432"  
    networks:
      - app-network
    volumes:
      - ./src/migrations:/docker-entrypoint-initdb.d 
    restart: always

networks:
  app-network:
    driver: bridge
